spring.application.name=Unidad-6-ejemplo-Elasticsearch-spring

# Configuración de Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# spring.elasticsearch.username=elastic
# spring.elasticsearch.password=changeme

# Opcional: configuraciones adicionales
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=30s

# Si usas Spring Data Elasticsearch
spring.data.elasticsearch.repositories.enabled=true