spring.application.name=Unidad-6-ejemplo-Elasticsearch-spring

# Configuración de Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# spring.elasticsearch.username=elastic
# spring.elasticsearch.password=changeme

# Opcional: configuraciones adicionales
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=30s

# Si usas Spring Data Elasticsearch
spring.data.elasticsearch.repositories.enabled=true

# Log a archivo
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.name=logs/app.log
# Nivel de logging
logging.level.root=INFO
logging.level.ar.edu.unq=DEBUG